### ISSUE TITLE
ModuleNotFoundError: No module named 'shicstats'

### ISSUE THREAD

**Issue by SBNoor** [kern-lab/diploSHIC#14]
Hi,

I am following the tutorial 'A soup to nuts example'. I am on 'Calculating feature vectors from simulations' section. However, when I run my bash script, it throws me an error:
ModuleNotFoundError: No module named 'shicstats'
And I haven't been able to figure out why that is so. 'shicstats.pyf' file is in diploSHIC folder where fvTools.py is. 
Help would be appreciated.

**Comment by SBNoor** [comment]
I was able to figure out the problem. Thank you

**Comment by SBNoor** [comment]
Sorry. I thought I was able to figure it out. But I keep on getting that error.

**Comment by andrewkern** [comment]
it sounds like the installation process didn't go okay. did you call `python setup.py install`? that will compile and install the diploSHIC python tools

**Comment by SBNoor** [comment]
Yes, I did. But it could be something went wrong during installation process. I'll install everything again. Thanks.

**Comment by SBNoor** [comment]
It's working now. Thank you :)
