### ISSUE TITLE
Error when making sweep training Windows

### ISSUE THREAD

**Issue by SBNoor** [kern-lab/diploSHIC#17]
I am trying to format the training set i.e. consolidate the training set into 5 files. However, instead of having 11 windows, I have 22 windows whereby window 10 and 11 would classify as sweep and rest of the windows as linked to a given sweep. The command tells me that 'sweepTrainingWindows' parameter can be a comma-separated list of windows. However, when I provide a comma-separated list of windows it raises an error. 
<img width="706" alt="screenshot 2019-02-12 at 10 23 40" src="https://user-images.githubusercontent.com/23297354/52624991-4e0b5c80-2eb0-11e9-8e48-c67342c85727.png">

The Command I enter is:
<img width="956" alt="screenshot 2019-02-12 at 10 15 43" src="https://user-images.githubusercontent.com/23297354/52624518-31225980-2eaf-11e9-9964-2ffdf3cdc349.png">

Could you please tell me why is the tool raising this error? Have I understood comma-separated list of windows in a wrong way?

**Comment by andrewkern** [comment]
Hi there. This error is arising because diploSHIC expects a _single_ sweep window. In the example above you are passing it two windows `10,11` and it thus diploSHIC doesn't know what to do.

**Comment by SBNoor** [comment]
But doesn't the manual say that sweepTrainingWindows parameter can be a comma-separated list of windows?

**Comment by andrewkern** [comment]
sorry for the confusion. the code is written to be general to this case, but the implementation hasn't been used (as far as I know). Just use a single sweep window and it should go fine. Do your training simulations have more than one sweep within them?

**Comment by SBNoor** [comment]
Yes, I have more than one sweep. But I'll try simulating data with a single sweep. Thanks.
