### ISSUE TITLE
What could be compared against for prediction result?

### ISSUE THREAD

**Issue by jtxtina** [kern-lab/diploSHIC#22]
Since there is no comparison in prediction part, I am wondering is there anything that we can adopt to compare with to get accuracy result or something similar(Like in training part)? To better evaluate the model.

**Comment by andrewkern** [comment]
Hi there-- if you know the true labels from a set of observations, then you can use the prediction mode with a trained classifier to assess accuracy on that set. 

Does that help?

**Comment by jtxtina** [comment]
Yeah. But, do you have any such observations or test datasets?

**Comment by jtxtina** [comment]
Btw, have you ever trained with human gene datasets? Like what you did in S/HIC.

**Comment by jtxtina** [comment]
I am currently using Tennesse Euro training set in SHIC to train here. For calculating feature vector from simulation step, I am troubled by masking file. Could you help me with this?
Thank you!

**Comment by jtxtina** [comment]
I have finished a successful run of training, but the val_accuracy is really low, around 0.38, anything could helpful?

**Comment by andrewkern** [comment]
> Yeah. But, do you have any such observations or test datasets?

you should use simulated data for this

**Comment by andrewkern** [comment]
> Btw, have you ever trained with human gene datasets? Like what you did in S/HIC.

i'm not sure what you mean.

**Comment by andrewkern** [comment]
> I am currently using Tennesse Euro training set in SHIC to train here. For calculating feature vector from simulation step, I am troubled by masking file. Could you help me with this?
> Thank you!

The masking file is a fasta formated file with N's in place of the bases you wish to mask out

**Comment by jtxtina** [comment]
> > Yeah. But, do you have any such observations or test datasets?
> 
> you should use simulated data for this

Well, I mean, if there is any real dataset for this?

**Comment by jtxtina** [comment]
> > Btw, have you ever trained with human gene datasets? Like what you did in S/HIC.
> 
> i'm not sure what you mean.

How does diploSHIC work with human gene datasets, rather than gambiae only?

**Comment by jtxtina** [comment]
> > I am currently using Tennesse Euro training set in SHIC to train here. For calculating feature vector from simulation step, I am troubled by masking file. Could you help me with this?
> > Thank you!
> 
> The masking file is a fasta formated file with N's in place of the bases you wish to mask out

Yes, I used hg19 as genome reference for Tennesse Euro simulations, but the training result is poor, could you help me with this?
