### ISSUE TITLE
Question about the calculation of Fay and Wu's H-test

### ISSUE THREAD

**Issue by S3nnyK** [kern-lab/diploSHIC#58]
I am currently reviewing your code and have encountered something that I find a bit puzzling. In the original paper "Hitchhiking Under Positive Darwinian Selection" by Justin C. Fay and Chung-I Wu, H is described as the "difference between theta_pi and theta_H," implying that "H = theta_H - theta_pi."

However, in fvTools.py, I noticed that fayWuH is calculated as "statVals["thetaH"][subWinIndex] - statVals["pi"][subWinIndex]". This seems to reverse the order. I was wondering if this version of fayWuH is commonly used in the population genetics community.

Thank you very much for your time and clarification.

**Comment by andrewkern** [comment]
it could very well be that we are using the opposite sign here, but it doesn't matter for our purposes what the sign of the statistic is.
