### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by oushujun** [kern-lab/diploSHIC#9]
CentOs 7
Python 3.6.6 :: Anaconda, Inc.

I was testing `fvecSim` using the mosquito data and found a bug:

`python diploSHIC.py fvecSim diploid hard_0.msOut.gz test_hard_0.diploid.fvec --totalPhysLen 55000 --maskFileName Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.accessible.fa.gz --chrArmsForMasking 3R`

Program output:
`file name='hard_0.msOut.gz'vcfForMaskFileName='None': not masking any genotypes!
reading masking data...reading Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.accessible.fa.gz
checked genotypes at 0 sites
Traceback (most recent call last):
  File "/opt/software/SHIC/diploSHIC/makeFeatureVecsForSingleMsDiploid.py", line 64, in <module>
    sampleToPopFileName=sampleToPopFileName)
ValueError: too many values to unpack (expected 2)
/opt/software/miniconda/4.4.10--GCC-4.9.4/bin/python /opt/software/SHIC/diploSHIC/makeFeatureVecsForSingleMsDiploid.py hard_0.msOut.gz 55000 11 Anopheles-gambiae-PEST_CHROMOSOMES_AgamP3.accessible.fa.gz None None None 0.75 3R 0.25 None test_hard_0.diploid.fvec`

When removing the `--maskFileName` and `--chrArmsForMasking` parameters, it runs fine.

BTW, is the program designed to sample the provided mask file *randomly* (or sequencially?) to mimic true data? 

Thanks,
Shujun

**Comment by andrewkern** [comment]
this looks like a bug that was recently introduced to the code. hold on and we will fix it.

**Comment by stsmall** [comment]
Hi @andrewkern , @oushujun,
I just cloned the repo and setup. Still getting the same error when I invoke --maskFileName and --chrArmsForMasking. Is there a work around?
thanks,
@stsmall

**Comment by andrewkern** [comment]
this was code that @dschride had changed recently but i don't believe he has pushed his patch to github. @dschride did you push the new masking version?

**Comment by oushujun** [comment]
I used the buggy version and not supplying any masking to the simulated
data - the genome I used is very good and only contains very limited Ns and
physical gaps, so I figure not making would not be too big a problem.

Shujun

**Comment by dschride** [comment]
Shujun, please pull the latest version and try again. The cause of this issue is that diploid mode did not support masking sites without also masking genotypes, but I have added this functionality. Try running again and the same manner and let me know if this issue is resolved.

**Comment by stsmall** [comment]
Thank you @dschride!
After this update the example data finishes without error. My data using diploid and a mask file also finished without error.

**Comment by dschride** [comment]
No problem!

**Comment by lokeyCEU** [comment]
I am having a similar problem
Ran the following
`python diploSHIC.py fvecSim diploid sims/TEST.ms sims/TEST.fvec --totalPhysLen 110000`

`/anaconda3/bin/python makeFeatureVecsForSingleMsDiploid.py sims/TEST.ms 110000 11 None None None None 0.75 all 0.25 None sims/TEST.fvec
file name='sims/TEST.ms'Traceback (most recent call last):
  File "makeFeatureVecsForSingleMsDiploid.py", line 17, in <module>
    trainingDataFileObj, sampleSize, numInstances = openMsOutFileForSequentialReading(trainingDataFileName)
  File "/diploSHIC/msTools.py", line 150, in openMsOutFileForSequentialReading
    program, numSamples, numSims = header.strip().split()[:3]
ValueError: not enough values to unpack (expected 3, got 1)`

I don't see anything wrong with my header do you?

Here is the .ms file in question.

[TEST.ms.txt](https://github.com/kern-lab/diploSHIC/files/2716632/TEST.ms.txt)

**Comment by lokeyCEU** [comment]
Fixed it, thanks.
